pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                     args '-e GOCACHE=/tmp/.cache/go-build -e GOPATH=/go'
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}